package flow.behavior;

/*Generated by MPS */

import jetbrains.mps.ide.modelchecker.platform.actions.SpecificChecker;
import java.util.List;
import jetbrains.mps.ide.findusages.model.SearchResult;
import jetbrains.mps.ide.modelchecker.platform.actions.ModelCheckerIssue;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.util.ProgressMonitor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.ide.modelchecker.platform.actions.ModelChecker;

public class StructureChecker extends SpecificChecker {

  @Override
  public List<SearchResult<ModelCheckerIssue>> checkModel(SModel model, ProgressMonitor progressContext) {

    final List<SearchResult<ModelCheckerIssue>> results = ListSequence.fromList(new ArrayList<SearchResult<ModelCheckerIssue>>());


    List<SNode> modelNodes = SModelOperations.nodes(model, MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, "jetbrains.mps.lang.core.structure.BaseConcept"));

    //   
    for (SNode node : ListSequence.fromList(modelNodes)) {

      // We would like to check if #instance of two is more than two or not, if yes, send an issue back 
      if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getConcept(0x3ac25d6afd494a5bL, 0x9c1ca6236d977d96L, 0x2068c047bc17596eL, "flow.structure.RootConcept"))) {
        System.out.println("is an instance of one");
        if (SNodeOperations.getNodeDescendants(node, MetaAdapterFactory.getConcept(0x3ac25d6afd494a5bL, 0x9c1ca6236d977d96L, 0x2068c047bc1763abL, "flow.structure.ChildConcept"), false, new SAbstractConcept[]{}).size() > 2) {
          SpecificChecker.addIssue(results, node, "Number of instances of Concept \"Two\" is greater than 2", ModelChecker.SEVERITY_ERROR, "FLOW language error", null);






        }

      }



      // checking for constraints 
    }


    return results;
  }



}
